listen:
  - "127.0.0.1"
upstreams:
  - address: "8.8.8.8"
    tls_name: "dns.google"
    port: 853
    tcp: 1
  - address: "8.8.4.4"
    tls_name: "dns.google"
    port: 853
    tcp: 1
  - address: "1.1.1.1"
    tls_name: "cloudflare-dns.com"
    port: 853
    tcp: 1
  - address: "1.0.0.1"
    tls_name: "cloudflare-dns.com"
    port: 853
    tcp: 1
  - address: "9.9.9.9"
    tls_name: "dns.quad9.net"
    port: 853
    tcp: 1
blacklist:
  url:
    - "https://pgl.yoyo.org/as/serverlist.php?hostformat=nohtml&showintro=0"
  domain:
    - "doubleclick.net"
    - "adclick.g.doubleclick.net"
